[default]
extend-ignore-identifiers-re = [
    "AttributeID.*Supress.*",
]

[default.extend-identifiers]
AttributeIDSupressMenu = "AttributeIDSupressMenu"

[default.extend-words]
INOUT = "INOUT"
WRONLY = "WRONLY"
nd = "nd"
iy = "iy"
HPE = "HPE"
alph = "alph"
gam = "gam"
Gam = "Gam"
strang = "strang"
Strang = "Strang"
TKE = "TKE"
HSA = "HSA"

[files]
extend-exclude = ["docs/documentation/references*", "tests/", "toolchain/cce_simulation_workgroup_256.sh"]
