blank_issues_enabled: false
contact_links:
  - name: Questions & support
    url: https://github.com/MFlowCode/MFC/discussions
    about: Get help, show results, and discuss ideas
  - name: Slack community
    url: https://join.slack.com/t/mflowcode/shared_invite/zt-y75wibvk-g~zztjknjYkK1hFgCuJxVw
    about: Join our Slack workspace for real-time discussion







