name: Check Line Counts
on: [push]

jobs:
  sz:
    name: Core MFC Line Difference
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code from PR branch
        uses: actions/checkout@v4
        with:
          path: pr

      - name: Checkout code from MFC master
        uses: actions/checkout@v4
        with:
          repository: MFlowCode/MFC
          ref:        master
          path:       base

      - name: Setup MFCs
        run: |
          BASE="$GITHUB_WORKSPACE/base"
          PR="$GITHUB_WORKSPACE/pr"
          cd $BASE
          ./mfc.sh count
          cd $PR
          ./mfc.sh count

      - name: Counting Lines
        run: |
          BASE="$GITHUB_WORKSPACE/base"
          PR="$GITHUB_WORKSPACE/pr"
          cd $BASE
          echo "___BASE______________"
          ./mfc.sh count
          cd $PR
          echo "___PR________________"
          ./mfc.sh count

      - name: Get Line Diff
        run: |
          BASE="$GITHUB_WORKSPACE/base"
          PR="$GITHUB_WORKSPACE/pr"
          cd $BASE
          export MFC_PR=$PR
          pwd
          ./mfc.sh count_diff

